### PR TITLE
Lu 2631 th gr refactor

### PR DESCRIPTION
**Pull request by GMReynolds**

### CODE REVIEW

**Review by bitmonkey — CHANGES_REQUESTED** [review]
@GMReynolds 

Few things to look at:

1) Linting

Flake8 reports a few things (attached below), run `./do.sh run python flake8` to run the linter

[lint_output.txt](https://github.com/ONSdigital/es-strata-sg/files/3441026/lint_output.txt)

2) Use `marshmallow` instead of the `get_environment` function

You should use a schema class in your `lambda_handler` function to parse the passed data and return any errors (Mike and others have use this already, can help if you need it) but the general gist is....

Since you're using a few environmental variables to set parameters, it's better to use a serialisation framework to parse the expected data and let the user know if something's not been supplied. 

For this we'll use `marshmallow` (https://marshmallow.readthedocs.io/en/2.x-line/) where you can use a schema class to define what parameters are expected and their types, you then just pass the environment dictionary and it will check for missing values / incorrect types e.g

```
from marshmallow import Schema, fields

class EnvSchema(Schema):
    my_value = fields.Str(required=True)

data, errors = EnvSchema().loads(os.environ)
if errors:
    raise ValueError(f"""Missing env params {errors}""")
```

This way the schema defines what's expected and will tell you about any errors, if there aren't any errors then the `data` dictionary variable will have the validated values in it for you to use.

3) Pass through values of variables into functions from the lambda handler.

You should pass through the values validated by marshmallow in the lambda through to individual functions like `send_sns_message` as function arguments.

4) Remove print statements

Not needed, these are from you debugging.

5) Need to test sad path

If you look at the coverage reports (`do.sh test --cov --cov-report html`) you'll see you're not hitting the exception blocks, you need a test to test what happens when something fails and triggers and exception,

**Comment by GMReynolds** [comment]
I think I have completed all that is required/ has been requested to be changed. Jira has some of the decisions documented.

**Comment by bitmonkey** [comment]
@Jordancooke Looks good other than some `flake8` issues to resolve:

Ran `./do.sh run python flake8` and got the attached warnings

[flake8_says_no.txt](https://github.com/ONSdigital/es-strata-sg/files/3500703/flake8_says_no.txt)

If you fix, bounce back to me with a clear run - I'll re-review n merge if all is well :grin:

**Review by bitmonkey — CHANGES_REQUESTED** [review]
@Jordancooke Looks good other than some `flake8` issues to resolve:

Ran `./do.sh run python flake8` and got the attached warnings

[flake8_says_no.txt](https://github.com/ONSdigital/es-strata-sg/files/3500703/flake8_says_no.txt)

If you fix, bounce back to me with a clear run - I'll re-review n merge if all is well :grin:

**Review by bitmonkey — APPROVED** [review]
Clean linter and test run, coverage good - Winner winner chicken dinner......merge is go.

**Pull request merged**
